# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'ClashMah' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # No external dependencies needed - using native Swift/UIKit only
  pod 'Alamofire'
  pod 'Nuke'
end
